### ISSUE TITLE
Python Scipt fails with abunch of errors

### ISSUE THREAD

**Issue by Zer0day-0** [yilin-wei98/INDELpred#2]
Dear @yilin-wei98, 

The python script clinical_processing_and_prediction.py fails with a bunch of errors. Starting with This. 

```ANNOVAR file read successfully
Traceback (most recent call last):
  File "/home/saurav/bintools/INDELpred/clinical_processing_and_prediction.py", line 91, in <module>
    total = total.loc[total['Length'] > 0 & total['Length'] < 100]
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/saurav/anaconda3/envs/INDELpred/lib/python3.11/site-packages/pandas/core/generic.py", line 1577, in __nonzero__
    raise ValueError(
ValueError: The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().
All steps completed!
```

I have initiated a pull request, for this. Apart from this, There seems to be a bunch of key errors. Please have a look.

```Traceback (most recent call last):
  File "/home/saurav/bintools/INDELpred/clinical_processing_and_prediction.py", line 137, in <module>
    clinical_data = total.loc[:, columns_list]
                    ~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "/home/saurav/anaconda3/lib/python3.12/site-packages/pandas/core/indexing.py", line 1184, in __getitem__
    return self._getitem_tuple(key)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/saurav/anaconda3/lib/python3.12/site-packages/pandas/core/indexing.py", line 1377, in _getitem_tuple
    return self._getitem_tuple_same_dim(tup)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/saurav/anaconda3/lib/python3.12/site-packages/pandas/core/indexing.py", line 1020, in _getitem_tuple_same_dim
    retval = getattr(retval, self.name)._getitem_axis(key, axis=i)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/saurav/anaconda3/lib/python3.12/site-packages/pandas/core/indexing.py", line 1420, in _getitem_axis
    return self._getitem_iterable(key, axis=axis)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/saurav/anaconda3/lib/python3.12/site-packages/pandas/core/indexing.py", line 1360, in _getitem_iterable
    keyarr, indexer = self._get_listlike_indexer(key, axis)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/saurav/anaconda3/lib/python3.12/site-packages/pandas/core/indexing.py", line 1558, in _get_listlike_indexer
    keyarr, indexer = ax._get_indexer_strict(key, axis_name)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/saurav/anaconda3/lib/python3.12/site-packages/pandas/core/indexes/base.py", line 6200, in _get_indexer_strict
    self._raise_if_missing(keyarr, indexer, axis_name)
  File "/home/saurav/anaconda3/lib/python3.12/site-packages/pandas/core/indexes/base.py", line 6252, in _raise_if_missing
    raise KeyError(f"{not_found} not in index")
KeyError: "['controls_AF_popmax', 'Func_p', 'ExonicFunc_b', 'ExonicFunc_p'] not in index"```

**Comment by yilin-wei98** [comment]
Thank you for your help in modifying the code. Regarding the missing value, I would like to ask if you downloaded the gnomad211_genome database. The command is as follows: annotate_variation.pl -buildver hg19 -downdb -webfrom annovar gnomad211_genome humandb/

**Comment by yilin-wei98** [comment]
Thank you for your help in modifying the code. I have no problem running here. Have you downloaded the ANNOVAR database?

**Comment by Zer0day-0** [comment]
Oh, It seems it is not backwards compatible I tried to run it with genomeAD 4.1 (latest release), but when running with genomeAD 211 genome and hg38. This is the error that the program ins throwing. 

``` ANNOVAR file read successfully
/home/saurav/bintools/INDELpred/clinical_processing_and_prediction.py:113: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.
For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.
  total[col].fillna(fill_values_Func[col], inplace=True)
/home/saurav/bintools/INDELpred/clinical_processing_and_prediction.py:122: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  data['Func_b'] = data['Func.refGene'].replace(dic_func_b)
/home/saurav/bintools/INDELpred/clinical_processing_and_prediction.py:124: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  data['Func_p'] = data['Func.refGene'].replace(dic_func_p)
/home/saurav/bintools/INDELpred/clinical_processing_and_prediction.py:126: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  data['Func'] = data['Func.refGene'].replace(dict_gene1)
/home/saurav/bintools/INDELpred/clinical_processing_and_prediction.py:128: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  data['ExonicFunc_b'] = data['ExonicFunc.refGene'].replace(dic_exon_func_b)
/home/saurav/bintools/INDELpred/clinical_processing_and_prediction.py:129: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  data['ExonicFunc_p'] = data['ExonicFunc.refGene'].replace(dic_exon_func_p)
/home/saurav/bintools/INDELpred/clinical_processing_and_prediction.py:130: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  data['ExonicFunc'] = data['ExonicFunc.refGene'].replace(dict_gene2)
Traceback (most recent call last):
  File "/home/saurav/bintools/INDELpred/clinical_processing_and_prediction.py", line 137, in <module>
    clinical_data = total.loc[:, columns_list]
                    ~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "/home/saurav/anaconda3/envs/INDELpred/lib/python3.11/site-packages/pandas/core/indexing.py", line 1184, in __getitem__
    return self._getitem_tuple(key)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/saurav/anaconda3/envs/INDELpred/lib/python3.11/site-packages/pandas/core/indexing.py", line 1377, in _getitem_tuple
    return self._getitem_tuple_same_dim(tup)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^   
  File "/home/saurav/anaconda3/envs/INDELpred/lib/python3.11/site-packages/pandas/core/indexing.py", line 1020, in _getitem_tuple_same_dim
    retval = getattr(retval, self.name)._getitem_axis(key, axis=i)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/saurav/anaconda3/envs/INDELpred/lib/python3.11/site-packages/pandas/core/indexing.py", line 1420, in _getitem_axis
    return self._getitem_iterable(key, axis=axis)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/saurav/anaconda3/envs/INDELpred/lib/python3.11/site-packages/pandas/core/indexing.py", line 1360, in _getitem_iterable
    keyarr, indexer = self._get_listlike_indexer(key, axis)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/saurav/anaconda3/envs/INDELpred/lib/python3.11/site-packages/pandas/core/indexing.py", line 1558, in _get_listlike_indexer
    keyarr, indexer = ax._get_indexer_strict(key, axis_name)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/saurav/anaconda3/envs/INDELpred/lib/python3.11/site-packages/pandas/core/indexes/base.py", line 6200, in _get_indexer_strict
    self._raise_if_missing(keyarr, indexer, axis_name)
  File "/home/saurav/anaconda3/envs/INDELpred/lib/python3.11/site-packages/pandas/core/indexes/base.py", line 6252, in _raise_if_missing
    raise KeyError(f"{not_found} not in index")
KeyError: "['Func_p', 'ExonicFunc_b', 'ExonicFunc_p'] not in index"
All steps completed!

```

**Comment by Zer0day-0** [comment]
The script thows an error like 

```python
Step 2: Running clinical_processing_and_prediction.py...
ANNOVAR file read successfully
Traceback (most recent call last):
  File "/home/saurav/bintools/INDELpred/clinical_processing_and_prediction.py", line 134, in <module>
    func_replace(total)
  File "/home/saurav/bintools/INDELpred/clinical_processing_and_prediction.py", line 123, in func_replace
    data = data.infer_objects(copy=False) #newline
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: NDFrame.infer_objects() got an unexpected keyword argument 'copy'
```
resolving this with the ``copy=False`` removed, we get another set of error. 

```python
Traceback (most recent call last):
  File "/home/saurav/bintools/INDELpred/clinical_processing_and_prediction.py", line 137, in <module>
    clinical_data = total.loc[:, columns_list]
                    ~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "/home/saurav/anaconda3/envs/INDELpred/lib/python3.11/site-packages/pandas/core/indexing.py", line 1067, in __getitem__
    return self._getitem_tuple(key)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/saurav/anaconda3/envs/INDELpred/lib/python3.11/site-packages/pandas/core/indexing.py", line 1256, in _getitem_tuple
    return self._getitem_tuple_same_dim(tup)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/saurav/anaconda3/envs/INDELpred/lib/python3.11/site-packages/pandas/core/indexing.py", line 924, in _getitem_tuple_same_dim
    retval = getattr(retval, self.name)._getitem_axis(key, axis=i)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/saurav/anaconda3/envs/INDELpred/lib/python3.11/site-packages/pandas/core/indexing.py", line 1301, in _getitem_axis
    return self._getitem_iterable(key, axis=axis)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/saurav/anaconda3/envs/INDELpred/lib/python3.11/site-packages/pandas/core/indexing.py", line 1239, in _getitem_iterable
    keyarr, indexer = self._get_listlike_indexer(key, axis)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/saurav/anaconda3/envs/INDELpred/lib/python3.11/site-packages/pandas/core/indexing.py", line 1432, in _get_listlike_indexer
    keyarr, indexer = ax._get_indexer_strict(key, axis_name)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/saurav/anaconda3/envs/INDELpred/lib/python3.11/site-packages/pandas/core/indexes/base.py", line 6070, in _get_indexer_strict
    self._raise_if_missing(keyarr, indexer, axis_name)
  File "/home/saurav/anaconda3/envs/INDELpred/lib/python3.11/site-packages/pandas/core/indexes/base.py", line 6133, in _raise_if_missing
    raise KeyError(f"{not_found} not in index")
KeyError: "['Func_p', 'ExonicFunc_b', 'ExonicFunc_p'] not in index"
```
investigation further into the key-error I see that the columns of the multianno files are as follows, and no columns of those names exist. 
 
```bash
Chr
Start
End
Ref
Alt
Func.refGene
Gene.refGene
GeneDetail.refGene
ExonicFunc.refGene
AAChange.refGene
AF
AF_popmax
AF_male
AF_female
AF_raw
AF_afr
AF_sas
AF_amr
AF_eas
AF_nfe
AF_fin
AF_asj
AF_oth
non_topmed_AF_popmax
non_neuro_AF_popmax
non_cancer_AF_popmax
controls_AF_popmax
Otherinfo1
Otherinfo2
Otherinfo3
Otherinfo4
Otherinfo5
Otherinfo6
Otherinfo7
Otherinfo8
Otherinfo9
Otherinfo10
Otherinfo11
```

as you can see there is no columns named "'Func_b', 'Func_p', 'ExonicFunc_b', 'ExonicFunc_p'". Going back to my ANNOVER code, I see 

```bash
/home/software/GenomicsApps/annovar/table_annovar.pl $INPUT_VCF /home/saurav/genomic_databases/humandb/ -buildver $REF_VER -out $OUTPUT_PREFIX -remove -protocol refGene,gnomad211_genome -operation g,f -nastring . -vcfinput -thread 40
```

**Comment by yilin-wei98** [comment]
Hello, maybe you can try to downgrade pandas to 1.5.3, these are all variables calculated in func_replace(total) in the code, but somehow only Func_b successfully calculated
